level-09/college_portal/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "static_pages#index"
  resources :departments, only: [:index, :create, :new, :show]
  resources :sections, only: [:index, :new, :create, :show]
  resources :students, only:[:index, :new, :create, :show]
end

level-09/college_portal/app/models/department.rb
class Department < ApplicationRecord

  #associations
  has_many :sections, dependent: :destroy
  has_many :students, :through => :sections, dependent: :destroy

  # validations
  validates :name, presence: true, uniqueness: true

  #callbacks
  before_save :convert_name_to_caps

  private

  def convert_name_to_caps
    name.upcase!
  end
end

level-09/college_portal/app/models/section.rb
class Section < ApplicationRecord

  #associations
  belongs_to :department
  has_many :students, dependent: :destroy

  #validations
  validates :name, presence: true, uniqueness: true
  validates :department_id, presence: true

  #callbacks
  before_save :convert_name_to_caps

  private

  def convert_name_to_caps
    name.upcase!
  end
end

level-09/college_portal/app/models/student.rb
class Student < ApplicationRecord

  #associations
  belongs_to :section
  belongs_to :department

  #validations
  validates :name, presence: true
  validates :section_id, presence: true
  validates :department_id, presence: true
  validates :email, uniqueness: true

  validate :validate_section_mapping

  # callbacks
  before_create :generate_roll_no

  private

  def validate_section_mapping
    section = Section.find_by id: section_id

    if section.nil?
      errors.add(:section, "Section does not exist")
    elsif section.department_id != department_id
      errors.add(:section, "Selected section doesn't belongs to selected department")
    end
  end

  def generate_roll_no
    max_count = Student.count
    department_name = department.name.downcase.gsub(/\s/, "-")
    section_name = section.name.downcase.gsub(/\s/, "-")
    self.roll_no = "#{department_name}-#{section_name}-#{max_count + 1}"
  end
end

level-09/college_portal/app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController

  before_action :authenticate_user!

  def index
    @departments = Department.all
  end

  def show
    @departments = Department.all
  end

  def new
    unless current_user.admin?
      flash[:danger] = "You are not allowed to access this page."
      redirect_to root_path
    end

    @department = Department.new
  end

  def create

    unless current_user.admin?
      flash[:danger] = "You are not allowed to access this page."
      redirect_to root_path
    end

    @department = Department.new(department_params)
    # @department.name.upcase! #This line is not needed here since it is now included in callback
    if @department.save
      redirect_to action: "index"
    else
      render "new"
    end
  end

  def show
  end

  private

  def department_params
    params[:department].permit(:name)
  end
end

level-09/college_portal/app/controllers/sections_controller.rb
class SectionsController < ApplicationController

  before_action :authenticate_user!

  def index
    if params[:department_id]
      @sections = Section.where(department_id: params[:department_id]).all
    else
      @sections = Section.all
    end
  end

  def new
    @section = Section.new
    @department_collection = Department.all.collect { |p| [p.name, p.id] }
  end

  def create
    @section = Section.new(section_params)
    # @section.name.upcase! #This is line is not needed here since it is now included in callback
    if @section.save
      redirect_to action: "index"
    else
      render "new"
    end
  end

  def show
  end

  private

  def section_params
    params[:section].permit(:name, :department_id)
  end
end

level-09/college_portal/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

level-09/college_portal/app/controllers/students_controller.rb
class StudentsController < ApplicationController

  before_action :authenticate_user!

  def index
    if (params[:department_id] && params[:section_id] && params[:id])
      @student = Student.find(params[:id])
      @section = Section.find(params[:section_id])
      @department = Department.find(params[:department_id])
      render "show"
    elsif (params[:department_id] && params[:section_id])
      @students = Student.where(department_id: params[:department_id], section_id: params[:section_id]).all
    else
      @students = Student.all
    end
  end

  def new
    @student = Student.new
    @section_collection = Section.all.collect { |p| [p.name, p.id, p.department_id] }
    @department_collection = Department.all.collect { |p| [p.name, p.id] }
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to action: "index"
    else
      flash[:danger] = @student.errors.values.join(", ")
      render "new"
    end
  end

  def show
  end

  private

  def student_params
    params[:student].permit(:name, :email, :roll_no, :section_id, :department_id, :id)
  end
end

level-09/college_portal/app/helpers/departments_helper.rb
module DepartmentsHelper
end

level-09/college_portal/app/helpers/sections_helper.rb
module SectionsHelper
end

level-09/college_portal/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

level-09/college_portal/app/helpers/students_helper.rb
module StudentsHelper
end

level-09/college_portal/app/views/departments/index.html.erb
<br>
<div class="row">
  <div class="col-md-10">
    <h2>Departments</h2>
  </div>
  <% if current_user.admin? %>
    <div class="col-md-2">
      <a class="btn btn-primary float-right" href="<%=new_department_path%>" role="button">Create</a>
    </div>
  <% end %>
</div>
<br>
<ul class="list-group">
  <% @departments.each do |department| %>
    <li class="list-group-item">
      <a href="<%= sections_path(department_id: department.id) %>">
        <%= department.name %>
      </a>
    </li>
  <% end %>
</ul>

level-09/college_portal/app/views/departments/new.html.erb
<h2>Create Department</h2>

<%= form_for(@department) do |f| %>
  <div class="form-group">
    <label>Name</label>
    <%= f.text_field :name, class: "form-control", placeholder: "Department Name", style: "text-transform: uppercase;", required: true%>
    <br/>
    <%= f.submit text: "create", class: "btn btn-primary" %>
  </div>
<% end %>

level-09/college_portal/app/views/sections/index.html.erb
<div class="row">
  <div class="col-md-10">
    <h2>Sections</h2>
  </div>
  <% if current_user.admin? %>
    <div class="col-md-2">
      <a class="btn btn-primary float-right" href="<%=new_section_path%>" role="button">Create</a>
    </div>
  <% end %>
</div>

<br/>

<ul class="list-group">
  <% @sections.each do |section| %>
    <li class="list-group-item"><a href="<%=students_path(section_id: section.id , department_id: section.department_id)%>"><%= section.name %></a></li>
  <% end %>
</ul>

level-09/college_portal/app/views/sections/new.html.erb
<h2>Create Section</h2>

<%= form_for(@section) do |f| %>
  <div class="form-group">
    <label>Name</label>
    <%= f.text_field :name, class: "form-control", placeholder: "Section Name", style: "text-transform: uppercase;", required: true%>
    <br/>
    <label>Department</label>
    <%= f.select :department_id, @department_collection, { prompt: 'Select Department' }, class: "form-control", required: true%>
    <br/>
    <%= f.submit text: "create", class: "btn btn-primary"%>
  </div>
<% end %>

level-09/college_portal/app/views/static_pages/index.html.erb
<div class="jumbotron">
  <h1 class="display-4">Welcome to College Portal</h1>
  <p class="lead">A unified view of college directory</p>
  <hr class="my-4">
  <p>You can see listing of Departments and Sections and create them as and when needed.</p>
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="<%= departments_path %>" role="button">Let's get started</a>
  </p>
</div>

level-09/college_portal/app/views/students/index.html.erb
<div class="row">
  <div class="col-md-10">
    <h2>Students</h2>
  </div>
  <% if current_user.admin? %>
    <div class="col-md-2">
      <a class="btn btn-primary float-right" href="<%=new_student_path%>" role="button">Create</a>
    </div>
  <% end %>
</div>

<br/>

<ul class="list-group">
  <% @students.each do |student| %>
    <li class="list-group-item"><a href="<%=students_path(id: student.id, section_id: student.section_id , department_id: student.department_id)%>"><%= student.name %></a></li>
  <% end %>
</ul>

level-09/college_portal/app/views/students/new.html.erb
<h2>Create Students</h2>

<%= form_for(@student) do |f| %>
  <div class="form-group">
    <label>Name</label>
    <%= f.text_field :name, class: "form-control", placeholder: "Student Name", required: true%>
    <br/>
    <label>Email</label>
    <%= f.text_field :email, class: "form-control", placeholder: "Student Email", required: true%>
    <br/>
    <label>Department</label>
    <%= f.select :department_id, @department_collection, { prompt: 'Select Department' }, class: "form-control", :onchange => "hidesec()", id: "dept_select", required: true%>
    <label>Section</label>
    <%= f.select :section_id, @section_collection, { prompt: 'Select Section' }, class: "form-control", id: "sec_select", required: true%>
    <br/>
    <%= f.submit text: "create", class: "btn btn-primary"%>
  </div>
<% end %>

<!-- Function to hide all the sections not belonging to the selected department -->
<script type = 'text/javascript'>
	function hidesec(){
		let secSelect = document.getElementById("sec_select");
		let deptSelect = document.getElementById("dept_select");
		const section_options = secSelect.options;
		const sections = <%= @section_collection.inspect.html_safe %>;

		for(i=secSelect.length-1; i>0; i-=1){
			if(sections[i-1][2]==deptSelect.value){
				section_options[i].disabled=false;
				section_options[i].style.display="";
			}
			else{
				section_options[i].disabled=true;
				section_options[i].style.display="none";
			}
		}
		secSelect.selectedIndex = 0;
	}
</script>

level-09/college_portal/app/views/students/show.html.erb
<h2><%= @student.name %></h2>

<h5><label for= "email" style="padding: 5px 0px;">Email</label>
<span id="email"
style="background-color: lightgrey; border-radius: 5px; margin-left: 5em; padding: 5px; display: inline-block; width: 80%; float: right; text-align: left;"><%= @student.email %></span>
</h5>

<br/>

<h5><label for= "roll_no" style="padding: 5px 0px;">Roll No.</label>
<span id="roll_no"
style="background-color: lightgrey; border-radius: 5px; margin-left: 5em; padding: 5px; display: inline-block; width: 80%; float: right; text-align: left;"><%= @student.roll_no %></span>
</h5>

<br/>

<h5><label for= "department" style="padding: 5px 0px;">Department</label>
<span id="department"
style="background-color: lightgrey; border-radius: 5px; margin-left: 5em; padding: 5px; display: inline-block; width: 80%; float: right; text-align: left;"><%= @department.name %></span>
</h5>

<br/>

<h5><label for="section" style="padding: 5px 0px;">Section</label>
<span id="section"
style="background-color: lightgrey; border-radius: 5px; margin-left: 5em; padding: 5px; display: inline-block; width: 80%; float: right; text-align: left; align-content: right;"><%= @section.name %></span>
</h5>